<?php
/** @noinspection AccessModifierPresentedInspection
 * @noinspection PhpUnusedAliasInspection
 * @noinspection UnknownInspectionInspection
 * @noinspection PhpUnused
 * @noinspection ReturnTypeCanBeDeclaredInspection
 */
namespace examples\newexample\repo;

use Exception;

/**
 * Generated by PdoOne Version 2.25 Date generated Fri, 11 Feb 2022 11:34:47 -0400.
 * EDIT THIS CODE.
 * @copyright (c) Jorge Castro C. MIT License  https://github.com/EFTEC/PdoOne
 * Class UserRepo
 * <pre>
 * $code=$pdoOne->generateCodeClassRepo(''users'',''examples\newexample\repo'','array('productcategories'=>'ProductCategoryRepo','products'=>'ProductRepo','users'=>'UserRepo',)','''');
 * </pre>
 */
class UserRepo extends AbstractUserRepo
{
    const ME=__CLASS__;
    


}
